import { NextPage } from 'next'
import { ReactNode } from 'react'

import Head from 'next/head'

import { Layout } from '../layout/Layout'

type PageProps = {
  title: string
  children: ReactNode
}

export const Page: NextPage<PageProps> = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>{children}</Layout>
      </main>
    </>
  )
}
